import "server-only";

/**
 * Customers who ordered on the old WooCommerce store, as one-way hashes.
 *
 * Used only to answer "has this address bought from us before?", so the
 * first-order discount cannot be claimed by an existing customer.
 *
 * ---------------------------------------------------------------------------
 * The data is NOT in this repository, and must not be put back.
 *
 * These are unsalted hashes of email addresses, and an email address carries
 * very little entropy. Anyone holding a list of addresses - and compilations of
 * billions are freely downloadable - can hash them and test membership. So
 * publishing the set is equivalent to publishing the customer list: it tells
 * the world which named individuals bought research peptides. That is the
 * client's customers and the client's liability, and it is why this repository
 * can be public while the list is not.
 *
 * The hashes live in the LEGACY_CUSTOMER_HASHES environment variable, comma
 * separated, generated by scripts/build-legacy-blocklist.mjs. Roughly 31KB,
 * comfortably inside Vercel's 64KB limit.
 * ---------------------------------------------------------------------------
 *
 * With the variable unset the set is empty and every address reads as new.
 * That is the deliberate failure mode: the worst case is a returning customer
 * getting a discount they should not have, which is a marketing cost. Failing
 * the other way would block real first-time buyers from an advertised offer at
 * the moment they are trying to spend money.
 */

function load(): ReadonlySet<string> {
  const raw = process.env.LEGACY_CUSTOMER_HASHES;
  if (!raw) {
    // Deploys without the variable still work; they just cannot recognise a
    // returning customer. Logged once, at startup, rather than per request.
    console.warn(
      "[legacy-customers] LEGACY_CUSTOMER_HASHES is not set - " +
        "first-order checks will treat every email as new."
    );
    return new Set();
  }
  return new Set(
    raw
      .split(",")
      .map((h) => h.trim().toLowerCase())
      .filter(Boolean)
  );
}

/** Parsed once per process, not per checkout. */
export const LEGACY_CUSTOMER_HASHES: ReadonlySet<string> = load();
