// GENERATED by scripts/build-woo-map.mjs - do not edit by hand.
//
// slug -> WooCommerce product and variation ids, so a mirrored order carries
// real product references rather than free text. Regenerate when the client
// adds or renames a product in WooCommerce.
//
// Generated from https://upgradebiolabs.com

export type WooVariation = { id: number; price: number; options: string[] };
export type WooProduct = { id: number; name: string; variations: WooVariation[] };

export const WOO_PRODUCTS: Record<string, WooProduct> = {
  "bac-water-3ml": {
    "id": 3092,
    "name": "BAC Water 3ml",
    "variations": [
      {
        "id": 3093,
        "price": 15,
        "options": [
          "3ml",
          "1-2"
        ]
      }
    ]
  },
  "cartalax-injectable": {
    "id": 2783,
    "name": "Cartalax",
    "variations": [
      {
        "id": 2786,
        "price": 59,
        "options": [
          "20 MG",
          "5+"
        ]
      },
      {
        "id": 2785,
        "price": 62,
        "options": [
          "20 MG",
          "3-5"
        ]
      },
      {
        "id": 2784,
        "price": 65,
        "options": [
          "20 MG",
          "1-2"
        ]
      }
    ]
  },
  "tesofensine-capsules": {
    "id": 2774,
    "name": "Tesofensine Capsules",
    "variations": [
      {
        "id": 2790,
        "price": 140,
        "options": [
          "250 MCG",
          "5+"
        ]
      },
      {
        "id": 2789,
        "price": 145,
        "options": [
          "250 MCG",
          "3-5"
        ]
      },
      {
        "id": 2788,
        "price": 149,
        "options": [
          "250 MCG",
          "1-2"
        ]
      }
    ]
  },
  "aod-9604-spray": {
    "id": 2186,
    "name": "AOD-9604 Spray",
    "variations": [
      {
        "id": 2278,
        "price": 80,
        "options": [
          "5 MG Bottle",
          "5+"
        ]
      },
      {
        "id": 2277,
        "price": 85,
        "options": [
          "5 MG Bottle",
          "3-5"
        ]
      },
      {
        "id": 2276,
        "price": 89,
        "options": [
          "5 MG Bottle",
          "1-2"
        ]
      }
    ]
  },
  "kpv-spray": {
    "id": 2184,
    "name": "KPV Spray",
    "variations": [
      {
        "id": 2275,
        "price": 80,
        "options": [
          "10 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 2274,
        "price": 85,
        "options": [
          "10 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 2273,
        "price": 89,
        "options": [
          "10 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "dihexa-semax-selank-spray": {
    "id": 2182,
    "name": "Dihexa - Semax - Selank <br> Spray",
    "variations": [
      {
        "id": 2281,
        "price": 172,
        "options": [
          "5/5/5 MG in each Bottle",
          "5+"
        ]
      },
      {
        "id": 2280,
        "price": 176,
        "options": [
          "5/5/5 MG in each Bottle",
          "3-5"
        ]
      },
      {
        "id": 2279,
        "price": 179,
        "options": [
          "5/5/5 MG in each Bottle",
          "1-2"
        ]
      }
    ]
  },
  "ara-290": {
    "id": 1982,
    "name": "ARA-290",
    "variations": [
      {
        "id": 1986,
        "price": 77,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1985,
        "price": 81,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1984,
        "price": 85,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "pinealon": {
    "id": 1977,
    "name": "Pinealon",
    "variations": [
      {
        "id": 1981,
        "price": 98,
        "options": [
          "20 MG",
          "5+"
        ]
      },
      {
        "id": 1980,
        "price": 104,
        "options": [
          "20 MG",
          "3-5"
        ]
      },
      {
        "id": 1979,
        "price": 109,
        "options": [
          "20 MG",
          "1-2"
        ]
      }
    ]
  },
  "ghk-cu-spray": {
    "id": 1969,
    "name": "GHK-CU Spray",
    "variations": [
      {
        "id": 2089,
        "price": 85,
        "options": [
          "100mg"
        ]
      }
    ]
  },
  "tz-2": {
    "id": 1625,
    "name": "TZ-2",
    "variations": [
      {
        "id": 1632,
        "price": 189,
        "options": [
          "20 MG",
          "5+"
        ]
      },
      {
        "id": 1631,
        "price": 200,
        "options": [
          "20 MG",
          "3-5"
        ]
      },
      {
        "id": 1630,
        "price": 210,
        "options": [
          "20 MG",
          "1-2"
        ]
      },
      {
        "id": 1629,
        "price": 104,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1628,
        "price": 109,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1627,
        "price": 115,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "rt-3": {
    "id": 1617,
    "name": "RT-3",
    "variations": [
      {
        "id": 2054,
        "price": 195,
        "options": [
          "20 MG",
          "5+"
        ]
      },
      {
        "id": 2053,
        "price": 202,
        "options": [
          "20 MG",
          "3-5"
        ]
      },
      {
        "id": 2052,
        "price": 215,
        "options": [
          "20 MG",
          "1-2"
        ]
      },
      {
        "id": 1799,
        "price": 135,
        "options": [
          "10 MG",
          "1-2"
        ]
      },
      {
        "id": 1798,
        "price": 128,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1618,
        "price": 122,
        "options": [
          "10 MG",
          "5+"
        ]
      }
    ]
  },
  "selank": {
    "id": 1261,
    "name": "SELANK",
    "variations": [
      {
        "id": 1330,
        "price": 82,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1329,
        "price": 86,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1328,
        "price": 89,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "semax-selank-spray": {
    "id": 1233,
    "name": "Semax / Selank Spray",
    "variations": [
      {
        "id": 1312,
        "price": 127,
        "options": [
          "5mg per bottle",
          "5+"
        ]
      },
      {
        "id": 1311,
        "price": 131,
        "options": [
          "5mg per bottle",
          "3-5"
        ]
      },
      {
        "id": 1310,
        "price": 135,
        "options": [
          "5mg per bottle",
          "1-2"
        ]
      }
    ]
  },
  "mk-677-capsules": {
    "id": 1083,
    "name": "MK-677 Capsules",
    "variations": [
      {
        "id": 1101,
        "price": 67.5,
        "options": [
          "12.5 MG Per Capsule",
          "5+"
        ]
      },
      {
        "id": 1100,
        "price": 71.25,
        "options": [
          "12.5 MG Per Capsule",
          "3-5"
        ]
      },
      {
        "id": 1099,
        "price": 75,
        "options": [
          "12.5 MG Per Capsule",
          "1-2"
        ]
      }
    ]
  },
  "mots-c": {
    "id": 993,
    "name": "MOTS-C",
    "variations": [
      {
        "id": 997,
        "price": 67.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 996,
        "price": 71.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 995,
        "price": 75,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "mt-ii": {
    "id": 980,
    "name": "MT II",
    "variations": [
      {
        "id": 992,
        "price": 45,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 991,
        "price": 47.5,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 990,
        "price": 50,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "aod-9604": {
    "id": 904,
    "name": "AOD-9604",
    "variations": [
      {
        "id": 1416,
        "price": 59,
        "options": [
          "5 MG",
          "5+"
        ]
      },
      {
        "id": 1415,
        "price": 62,
        "options": [
          "5 MG",
          "3-5"
        ]
      },
      {
        "id": 1414,
        "price": 65,
        "options": [
          "5 MG",
          "1-2"
        ]
      }
    ]
  },
  "methylene-blue": {
    "id": 693,
    "name": "Methylene Blue",
    "variations": [
      {
        "id": 986,
        "price": 32,
        "options": [
          "12 MG/ML",
          "5+"
        ]
      },
      {
        "id": 985,
        "price": 32,
        "options": [
          "12 MG/ML",
          "3-5"
        ]
      },
      {
        "id": 984,
        "price": 32,
        "options": [
          "12 MG/ML",
          "1-2"
        ]
      }
    ]
  },
  "the-hair-blendminoxidil-ru-58841-finasteride": {
    "id": 688,
    "name": "The Hair Blend(Minoxidil, RU-58841, Finasteride)",
    "variations": [
      {
        "id": 853,
        "price": 125,
        "options": [
          "10%, 25 MG/ML, 500 MCG/ML",
          "1-2"
        ]
      },
      {
        "id": 847,
        "price": 112.5,
        "options": [
          "10%, 25 MG/ML, 500 MCG/ML",
          "5+"
        ]
      },
      {
        "id": 689,
        "price": 118.75,
        "options": [
          "10%, 25 MG/ML, 500 MCG/ML",
          "3-5"
        ]
      }
    ]
  },
  "slu-pp-332-capsules": {
    "id": 683,
    "name": "SLU-PP-332 CAPSULES",
    "variations": [
      {
        "id": 1030,
        "price": 85,
        "options": [
          "250 MCG",
          "5+"
        ]
      },
      {
        "id": 1029,
        "price": 85,
        "options": [
          "250 MCG",
          "3-5"
        ]
      },
      {
        "id": 1028,
        "price": 85,
        "options": [
          "250 MCG",
          "1-2"
        ]
      }
    ]
  },
  "kpv-capsules": {
    "id": 675,
    "name": "KPV Capsules",
    "variations": [
      {
        "id": 1184,
        "price": 72.9,
        "options": [
          "500 MCG Per Capsule",
          "5+"
        ]
      },
      {
        "id": 1183,
        "price": 81,
        "options": [
          "500 MCG Per Capsule",
          "3-5"
        ]
      },
      {
        "id": 1182,
        "price": 90,
        "options": [
          "500 MCG Per Capsule",
          "1-2"
        ]
      }
    ]
  },
  "klow-capsulesbpc-157-tb-500-kpv-ghk-cu": {
    "id": 671,
    "name": "KLOW Capsules(BPC-157, TB-500, KPV, GHK-Cu)",
    "variations": [
      {
        "id": 1194,
        "price": 135,
        "options": [
          "500 MCG, 1MG Per Capsule",
          "5+"
        ]
      },
      {
        "id": 1193,
        "price": 142.5,
        "options": [
          "500 MCG, 1MG Per Capsule",
          "3-5"
        ]
      },
      {
        "id": 1192,
        "price": 150,
        "options": [
          "500 MCG, 1MG Per Capsule",
          "1-2"
        ]
      }
    ]
  },
  "ghk-cu-capsules": {
    "id": 666,
    "name": "GHK-Cu Capsules",
    "variations": [
      {
        "id": 1203,
        "price": 78,
        "options": [
          "2 MG Per Capsule",
          "5+"
        ]
      },
      {
        "id": 1202,
        "price": 81,
        "options": [
          "2 MG Per Capsule",
          "3-5"
        ]
      },
      {
        "id": 1201,
        "price": 85,
        "options": [
          "2 MG Per Capsule",
          "1-2"
        ]
      }
    ]
  },
  "bpc-157-capsules": {
    "id": 661,
    "name": "BPC-157 Capsules",
    "variations": [
      {
        "id": 1207,
        "price": 103.5,
        "options": [
          "500 MCG",
          "5+"
        ]
      },
      {
        "id": 1206,
        "price": 109.25,
        "options": [
          "500 MCG",
          "3-5"
        ]
      },
      {
        "id": 1205,
        "price": 115,
        "options": [
          "500 MCG",
          "1-2"
        ]
      }
    ]
  },
  "5-amino-1-mq": {
    "id": 657,
    "name": "5 Amino 1 MQ",
    "variations": [
      {
        "id": 1333,
        "price": 112.5,
        "options": [
          "50 MG Per Capsule",
          "5+"
        ]
      },
      {
        "id": 1332,
        "price": 118.75,
        "options": [
          "50 MG Per Capsule",
          "3-5"
        ]
      },
      {
        "id": 1331,
        "price": 125,
        "options": [
          "50 MG Per Capsule",
          "1-2"
        ]
      }
    ]
  },
  "semax-spray": {
    "id": 648,
    "name": "Semax Spray",
    "variations": [
      {
        "id": 1640,
        "price": 85,
        "options": [
          "5mg per bottle",
          "5+"
        ]
      },
      {
        "id": 1639,
        "price": 87,
        "options": [
          "5mg per bottle",
          "3-5"
        ]
      },
      {
        "id": 1638,
        "price": 89,
        "options": [
          "5mg per bottle",
          "1-2"
        ]
      }
    ]
  },
  "pt-141-spray": {
    "id": 644,
    "name": "PT-141 Spray",
    "variations": [
      {
        "id": 1197,
        "price": 112,
        "options": [
          "10 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1196,
        "price": 115,
        "options": [
          "10 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1195,
        "price": 118,
        "options": [
          "10 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "oxytocin-spray": {
    "id": 639,
    "name": "Oxytocin Spray",
    "variations": [
      {
        "id": 1180,
        "price": 83,
        "options": [
          "50 MCG per spray",
          "5+"
        ]
      },
      {
        "id": 1179,
        "price": 86,
        "options": [
          "50 MCG per spray",
          "3-5"
        ]
      },
      {
        "id": 1178,
        "price": 89,
        "options": [
          "50 MCG per spray",
          "1-2"
        ]
      }
    ]
  },
  "nad-500-spray": {
    "id": 635,
    "name": "NAD+ 500 Spray",
    "variations": [
      {
        "id": 1172,
        "price": 109,
        "options": [
          "500 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1171,
        "price": 109,
        "options": [
          "500 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1170,
        "price": 109,
        "options": [
          "500 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "glutathione-nasal-spray": {
    "id": 630,
    "name": "Glutathione Nasal Spray",
    "variations": [
      {
        "id": 1166,
        "price": 76.5,
        "options": [
          "500 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1165,
        "price": 80.75,
        "options": [
          "500 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1164,
        "price": 85,
        "options": [
          "500 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "dsip-spray": {
    "id": 625,
    "name": "DSIP Spray",
    "variations": [
      {
        "id": 1157,
        "price": 79,
        "options": [
          "5 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1156,
        "price": 82,
        "options": [
          "5 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1155,
        "price": 85,
        "options": [
          "5 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "wolverine-blend-spraybpc-157-tb-500": {
    "id": 621,
    "name": "Wolverine Blend Spray(BPC-157, TB-500)",
    "variations": [
      {
        "id": 1151,
        "price": 123,
        "options": [
          "5 MG, 5 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1150,
        "price": 126,
        "options": [
          "5 MG, 5 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1149,
        "price": 129,
        "options": [
          "5 MG, 5 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "bpc-157-spray": {
    "id": 617,
    "name": "BPC-157 Spray",
    "variations": [
      {
        "id": 1145,
        "price": 85,
        "options": [
          "5 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1144,
        "price": 87,
        "options": [
          "5 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1143,
        "price": 89,
        "options": [
          "5 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "tesamorelin-ipamorelin-blend": {
    "id": 614,
    "name": "Tesamorelin, Ipamorelin Blend",
    "variations": [
      {
        "id": 1141,
        "price": 112,
        "options": [
          "10 MG/ 5 MG",
          "5+"
        ]
      },
      {
        "id": 1140,
        "price": 118,
        "options": [
          "10 MG/ 5 MG",
          "3-5"
        ]
      },
      {
        "id": 1139,
        "price": 125,
        "options": [
          "10 MG/ 5 MG",
          "1-2"
        ]
      }
    ]
  },
  "cjc-1295-no-dac-ipamorelin-blend": {
    "id": 611,
    "name": "CJC 1295 no DAC, Ipamorelin Blend",
    "variations": [
      {
        "id": 1137,
        "price": 76.5,
        "options": [
          "5 MG/ 5 MG",
          "5+"
        ]
      },
      {
        "id": 1136,
        "price": 80.75,
        "options": [
          "5 MG/ 5 MG",
          "3-5"
        ]
      },
      {
        "id": 1135,
        "price": 85,
        "options": [
          "5 MG/ 5 MG",
          "1-2"
        ]
      }
    ]
  },
  "klow-blendbpc-157-tb-500-kpv-ghk-cu": {
    "id": 604,
    "name": "KLOW Blend(BPC-157, TB-500, KPV, GHK-Cu)",
    "variations": [
      {
        "id": 1132,
        "price": 157.5,
        "options": [
          "10 MG/ 10 MG/ 10 MG/ 50 MG",
          "5+"
        ]
      },
      {
        "id": 1131,
        "price": 166.25,
        "options": [
          "10 MG/ 10 MG/ 10 MG/ 50 MG",
          "3-5"
        ]
      },
      {
        "id": 1130,
        "price": 175,
        "options": [
          "10 MG/ 10 MG/ 10 MG/ 50 MG",
          "1-2"
        ]
      }
    ]
  },
  "wolverine-blendbpc-157-tb-500": {
    "id": 599,
    "name": "Wolverine Blend(BPC-157, TB-500)",
    "variations": [
      {
        "id": 1128,
        "price": 85.5,
        "options": [
          "5 MG/ 5 MG",
          "5+"
        ]
      },
      {
        "id": 1127,
        "price": 90.25,
        "options": [
          "5 MG/ 5 MG",
          "3-5"
        ]
      },
      {
        "id": 1126,
        "price": 95,
        "options": [
          "5 MG/ 5 MG",
          "1-2"
        ]
      },
      {
        "id": 1125,
        "price": 126,
        "options": [
          "10 MG/ 10 MG",
          "5+"
        ]
      },
      {
        "id": 1124,
        "price": 133,
        "options": [
          "10 MG/ 10 MG",
          "3-5"
        ]
      },
      {
        "id": 1123,
        "price": 140,
        "options": [
          "10 MG/ 10 MG",
          "1-2"
        ]
      }
    ]
  },
  "glow-blendbpc-157-tb-500-ghk-cu": {
    "id": 596,
    "name": "Glow Blend(BPC-157, TB-500, GHK-Cu)",
    "variations": [
      {
        "id": 1121,
        "price": 157.5,
        "options": [
          "10 MG/ 10 MG/ 50 MG",
          "5+"
        ]
      },
      {
        "id": 1120,
        "price": 166.25,
        "options": [
          "10 MG/ 10 MG/ 50 MG",
          "3-5"
        ]
      },
      {
        "id": 1119,
        "price": 175,
        "options": [
          "10 MG/ 10 MG/ 50 MG",
          "1-2"
        ]
      }
    ]
  },
  "bac-water-hospira-brand": {
    "id": 590,
    "name": "BAC Water - Hospira brand",
    "variations": [
      {
        "id": 1040,
        "price": 42,
        "options": [
          "30 ML",
          "1-2"
        ]
      }
    ]
  },
  "thymosin-alpha-1": {
    "id": 587,
    "name": "THYMOSIN ALPHA-1",
    "variations": [
      {
        "id": 1039,
        "price": 94.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1038,
        "price": 99.75,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1037,
        "price": 105,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "tesamorelin": {
    "id": 584,
    "name": "TESAMORELIN",
    "variations": [
      {
        "id": 1036,
        "price": 85.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1035,
        "price": 90.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1034,
        "price": 95,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "tb-500": {
    "id": 581,
    "name": "TB-500",
    "variations": [
      {
        "id": 1027,
        "price": 67.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1026,
        "price": 71.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1025,
        "price": 75,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "ss-31": {
    "id": 579,
    "name": "SS-31",
    "variations": [
      {
        "id": 1022,
        "price": 85.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1021,
        "price": 90.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1020,
        "price": 95,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "sermorelin": {
    "id": 561,
    "name": "SERMORELIN",
    "variations": [
      {
        "id": 1019,
        "price": 49.5,
        "options": [
          "5 MG",
          "5+"
        ]
      },
      {
        "id": 1018,
        "price": 52.25,
        "options": [
          "5 MG",
          "3-5"
        ]
      },
      {
        "id": 1017,
        "price": 55,
        "options": [
          "5 MG",
          "1-2"
        ]
      }
    ]
  },
  "semax": {
    "id": 558,
    "name": "SEMAX",
    "variations": [
      {
        "id": 1014,
        "price": 54,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1013,
        "price": 57,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1012,
        "price": 60,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "selank-spray": {
    "id": 555,
    "name": "Selank Spray",
    "variations": [
      {
        "id": 1228,
        "price": 83,
        "options": [
          "5 MG Per Bottle",
          "5+"
        ]
      },
      {
        "id": 1227,
        "price": 86,
        "options": [
          "5 MG Per Bottle",
          "3-5"
        ]
      },
      {
        "id": 1226,
        "price": 89,
        "options": [
          "5 MG Per Bottle",
          "1-2"
        ]
      }
    ]
  },
  "pt-141": {
    "id": 551,
    "name": "PT-141",
    "variations": [
      {
        "id": 1006,
        "price": 54,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 1005,
        "price": 57,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 1004,
        "price": 60,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "nad": {
    "id": 535,
    "name": "NAD+",
    "variations": [
      {
        "id": 1003,
        "price": 85.5,
        "options": [
          "1000 MG",
          "5+"
        ]
      },
      {
        "id": 1002,
        "price": 90.25,
        "options": [
          "1000 MG",
          "3-5"
        ]
      },
      {
        "id": 1001,
        "price": 95,
        "options": [
          "1000 MG",
          "1-2"
        ]
      },
      {
        "id": 1000,
        "price": 54,
        "options": [
          "500 MG",
          "5+"
        ]
      },
      {
        "id": 999,
        "price": 57,
        "options": [
          "500 MG",
          "3-5"
        ]
      },
      {
        "id": 998,
        "price": 60,
        "options": [
          "500 MG",
          "1-2"
        ]
      }
    ]
  },
  "ll-37": {
    "id": 529,
    "name": "LL-37",
    "variations": [
      {
        "id": 946,
        "price": 85.5,
        "options": [
          "5 MG",
          "5+"
        ]
      },
      {
        "id": 945,
        "price": 90.25,
        "options": [
          "5 MG",
          "3-5"
        ]
      },
      {
        "id": 944,
        "price": 95,
        "options": [
          "5 MG",
          "1-2"
        ]
      }
    ]
  },
  "kpv": {
    "id": 526,
    "name": "KPV",
    "variations": [
      {
        "id": 943,
        "price": 67.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 942,
        "price": 71.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 941,
        "price": 75,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "kisspeptin-10": {
    "id": 523,
    "name": "KISSPEPTIN-10",
    "variations": [
      {
        "id": 939,
        "price": 54,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 938,
        "price": 57,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 937,
        "price": 60,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "ipamorelin": {
    "id": 520,
    "name": "Ipamorelin",
    "variations": [
      {
        "id": 936,
        "price": 63,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 935,
        "price": 66.5,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 934,
        "price": 70,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "igf-1-lr3": {
    "id": 517,
    "name": "IGF-1 LR3",
    "variations": [
      {
        "id": 933,
        "price": 88.2,
        "options": [
          "1 MG",
          "5+"
        ]
      },
      {
        "id": 932,
        "price": 93.1,
        "options": [
          "1 MG",
          "3-5"
        ]
      },
      {
        "id": 931,
        "price": 98,
        "options": [
          "1 MG",
          "1-2"
        ]
      }
    ]
  },
  "glutathione": {
    "id": 514,
    "name": "Glutathione",
    "variations": [
      {
        "id": 930,
        "price": 115,
        "options": [
          "1500mg",
          "5+"
        ]
      },
      {
        "id": 929,
        "price": 120,
        "options": [
          "1500mg",
          "3-5"
        ]
      },
      {
        "id": 928,
        "price": 125,
        "options": [
          "1500mg",
          "1-2"
        ]
      }
    ]
  },
  "ghk-cu": {
    "id": 511,
    "name": "GHK-Cu",
    "variations": [
      {
        "id": 927,
        "price": 49.5,
        "options": [
          "50 MG",
          "5+"
        ]
      },
      {
        "id": 926,
        "price": 52.25,
        "options": [
          "50 MG",
          "3-5"
        ]
      },
      {
        "id": 925,
        "price": 55,
        "options": [
          "50 MG",
          "1-2"
        ]
      }
    ]
  },
  "epithalon": {
    "id": 507,
    "name": "EPITHALON",
    "variations": [
      {
        "id": 924,
        "price": 49.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 923,
        "price": 52.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 922,
        "price": 55,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "dsip": {
    "id": 504,
    "name": "DSIP",
    "variations": [
      {
        "id": 921,
        "price": 54,
        "options": [
          "5 MG",
          "5+"
        ]
      },
      {
        "id": 920,
        "price": 57,
        "options": [
          "5 MG",
          "3-5"
        ]
      },
      {
        "id": 919,
        "price": 60,
        "options": [
          "5 MG",
          "1-2"
        ]
      }
    ]
  },
  "cjc-1295-no-dac": {
    "id": 501,
    "name": "CJC 1295 no DAC",
    "variations": [
      {
        "id": 917,
        "price": 63,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 916,
        "price": 66.5,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 915,
        "price": 70,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "cagrilintide": {
    "id": 498,
    "name": "Cagrilintide",
    "variations": [
      {
        "id": 914,
        "price": 121.5,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 913,
        "price": 128.25,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 912,
        "price": 135,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  },
  "bpc-157": {
    "id": 492,
    "name": "BPC-157",
    "variations": [
      {
        "id": 911,
        "price": 81,
        "options": [
          "10 MG",
          "5+"
        ]
      },
      {
        "id": 910,
        "price": 85.5,
        "options": [
          "10 MG",
          "3-5"
        ]
      },
      {
        "id": 909,
        "price": 90,
        "options": [
          "10 MG",
          "1-2"
        ]
      }
    ]
  }
};
