/**
 * Generates src/lib/woo-products.ts - the slug -> WooCommerce id map.
 *
 * Orders are mirrored into WooCommerce so the client's existing fulfilment
 * stack (ShipStation, UPS Labels, UBL Invoices) keeps working. For a line to
 * look native there - and to decrement the right stock - it has to carry
 * Woo's own product_id and variation_id, not just a name.
 *
 * Every one of their 61 products is a *variable* product whose variations are
 * keyed by two attributes: the fill (e.g. "10 MG") and a quantity band
 * ("1-2", "3-5", "5+"). Those bands are exactly our bulk tiers, so a line's
 * variation is a function of (slug, size, quantity).
 *
 * Run when the client adds or renames a product:
 *   WOO_CONSUMER_KEY=ck_… WOO_CONSUMER_SECRET=cs_… node scripts/build-woo-map.mjs
 */

import fs from "node:fs";

const BASE = process.env.WOO_STORE_URL ?? "https://upgradebiolabs.com";
const KEY = process.env.WOO_CONSUMER_KEY;
const SECRET = process.env.WOO_CONSUMER_SECRET;

if (!KEY || !SECRET) {
  console.error("Set WOO_CONSUMER_KEY and WOO_CONSUMER_SECRET.");
  process.exit(1);
}

const auth = "Basic " + Buffer.from(`${KEY}:${SECRET}`).toString("base64");
const get = async (path) => {
  const res = await fetch(`${BASE}/wp-json/wc/v3${path}`, {
    headers: { Authorization: auth },
  });
  if (!res.ok) throw new Error(`${path} -> ${res.status}`);
  return res.json();
};

const products = await get("/products?per_page=100&status=any");
console.log(`fetched ${products.length} products`);

const map = {};
for (const p of products) {
  if (p.slug === "test-product") continue;

  const variations = p.type === "variable" ? await get(`/products/${p.id}/variations?per_page=100`) : [];

  map[p.slug] = {
    id: p.id,
    name: p.name,
    variations: variations.map((v) => ({
      id: v.id,
      price: Number(v.price),
      // Attribute order is not guaranteed, so the band is found by shape
      // rather than by position: it is the one that looks like a range.
      options: v.attributes.map((a) => String(a.option ?? "")),
    })),
  };
  process.stdout.write(".");
}
console.log(`\nmapped ${Object.keys(map).length} products`);

const out = `// GENERATED by scripts/build-woo-map.mjs - do not edit by hand.
//
// slug -> WooCommerce product and variation ids, so a mirrored order carries
// real product references rather than free text. Regenerate when the client
// adds or renames a product in WooCommerce.
//
// Generated from ${BASE}

export type WooVariation = { id: number; price: number; options: string[] };
export type WooProduct = { id: number; name: string; variations: WooVariation[] };

export const WOO_PRODUCTS: Record<string, WooProduct> = ${JSON.stringify(map, null, 2)};
`;

fs.writeFileSync("src/lib/woo-products.ts", out);
console.log("wrote src/lib/woo-products.ts");
